[build]
builder = "dockerfile"  # Используем кастомный Dockerfile
dockerfilePath = "Dockerfile"  # Путь к Dockerfile

[deploy]
startCommand = "n8n start"  # Команда запуска
healthcheckPath = "/"  # Путь для проверки состояния
healthcheckTimeout = 100  # Таймаут проверки (в секундах)
restartPolicyType = "ON_FAILURE"  # Перезапуск при сбое
restartPolicyMaxRetries = 3  # Максимум 3 попытки перезапуска

[deploy.envs]
N8N_PORT = "5678"  # Порт n8n
N8N_HOST = "0.0.0.0"  # Хост для доступности
N8N_PROTOCOL = "http"  # Протокол
N8N_USER_FOLDER = "/data"  # Папка для данных

# Опционально: настройка Volume для сохранения данных
[deploy.volumes]
"/data" = { source = "n8n-data", type = "persistent" }  # Подключение Volume для /data