[build]
builder = "nixpacks"  # Используем Nixpacks для автоматической сборки

[nixpacksPlan]
  [nixpacksPlan.phases.setup]
    nixPkgs = ["nodejs-20_x", "pnpm-10_x"]  # Указываем Node.js 20 и pnpm

  [nixpacksPlan.phases.build]
    cmds = ["pnpm install --production"]  # Устанавливаем зависимости

[deploy]
startCommand = "sh -c 'cd packages/cli/bin && ./n8n start'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
N8N_PORT = "5678"
N8N_HOST = "0.0.0.0"
N8N_PROTOCOL = "http"
N8N_USER_FOLDER = "/data"

[deploy.volumes]
"/data" = { source = "n8n-data", type = "persistent" }